
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-api
spec:
  selector:
    matchLabels:
      app: database-api
  template:
    metadata:
      labels:
        app: database-api
    spec:
      containers:
      - name: database-api
        image: database-api:1.0
        imagePullPolicy: IfNotPresent # don't go to internet, check locally
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5500

